project_id = "csmlelbyyqsiymsqfeuj"

[functions.send-push-notification]
verify_jwt = false

[functions.export-history]
verify_jwt = false

[functions.vapid-public-key]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-password-recovery]
verify_jwt = false